In [1]:
import pandas as pd
from glob import glob

In [2]:
usecols_csv = [
    # "ODB Name",
    # "Step",
    # "Frame",
    # "Part Instance Name",
    "    Node Label",
    "X",
    "Y",
    "Z",
    # "Section Name",
    # "Material Name",
    # "Section Point",
    "          U-U1",
    "          U-U2",
    "          U-U3",
]

usecols_xlsx = [
    # "ODB Name",
    # "Step",
    # "Frame",
    # "Part Instance Name",
    "    Node Label",
    "X",
    "Y",
    "Z",
    # "Section Name",
    # "Material Name",
    # "Section Point",
    "          U-U1",
    "          U-U2",
    "          U-U3",
    "U1 reverse",
    "U2 reverse",
    "U3 reverse",
    "X reverse",
    "Y reverse",
    "Z reverse",
]

dtypes = {
    "    Node Label": "int32",
    "X": "float64",
    "Y": "float64",
    "Z": "float64",
    "          U-U1": "float64",
    "          U-U2": "float64",
    "          U-U3": "float64",
    "U1 reverse": "float64",
    "U2 reverse": "float64",
    "U3 reverse": "float64",
    "X reverse": "float64",
    "Y reverse": "float64",
    "Z reverse": "float64",
}

renames = {
    "    Node Label": "Node Label",
    "          U-U1": "U-U1",
    "          U-U2": "U-U2",
    "          U-U3": "U-U3",
}

In [ ]:
# files = glob("../excel/*.xlsx")
# if len(files) == 1:
#     xlsx_path = files[0]
# else:
#     print("csvファイルが複数あります。")
#     print("ファイルを一つにしてください。")

In [11]:
files = glob("../input/*.csv")
if len(files) > 1:
    print("csvファイルが複数あります。ファイルを一つにしてください。")
else:
    csv_path = files[0]
df_csv = pd.read_csv(csv_path, usecols=usecols_csv, dtype=dtypes)
df_csv = df_csv.rename(columns=renames)
check_size = 1000
df_csv.iloc[:check_size].to_csv(f"../input_check_{check_size}.csv", index=False)
df_csv.head()

   Node Label        X        Y          Z     U-U1      U-U2      U-U3
0     8855713  616.782  129.669  -17.60680 -5.33949 -2.393390  10.69430
1     8855714 -538.910  527.412  102.59300  4.23937 -1.226520   1.55069
2     8855715  539.022  527.323  103.39300 -1.90947 -1.093000   2.76840
3     8855716 -617.058  126.759  -18.69680  8.54398 -1.761720   6.39717
4     8855717 -151.742 -286.211    4.56324  2.54304 -0.840559  -1.79094

In [5]:
prospect_coefficient = 1
df_csv["X_new"] = df_csv["X"] + df_csv["U-U1"] * -1 * prospect_coefficient
df_csv["Y_new"] = df_csv["Y"] + df_csv["U-U2"] * -1 * prospect_coefficient
df_csv["Z_new"] = df_csv["Z"] + df_csv["U-U3"] * -1 * prospect_coefficient
df_csv.head()

,Node Label,X,Y,Z,U-U1,U-U2,U-U3,X_new,Y_new,Z_new
0,8855713,616.782,129.669,-17.60680,-5.33949,-2.393390,10.69430,622.12149,132.062390,-28.30110
1,8855714,-538.910,527.412,102.59300,4.23937,-1.226520,1.55069,-543.14937,528.638520,101.04231
2,8855715,539.022,527.323,103.39300,-1.90947,-1.093000,2.76840,540.93147,528.416000,100.62460
3,8855716,-617.058,126.759,-18.69680,8.54398,-1.761720,6.39717,-625.60198,128.520720,-25.09397
4,8855717,-151.742,-286.211,4.56324,2.54304,-0.840559,-1.79094,-154.28504,-285.370441,6.35418

In [6]:
df_csv.to_csv("../output/output.csv")